### PR TITLE
Fixes for launcher.config / WorldQueue.config XML Changes and version bump to 0.2.1

### PR DESCRIPTION
**Pull request by nwestfal**
Fixes for pylotro following format changes to WorldQueue.config by Turbine on 20-Nov-2014 which broke pylotro functionality.  Initial patches by blosco posted to LOTRO forums in the following thread, with additional patches provided by myself to complete the new argument template.

See relevant thread here:
https://www.lotro.com/forums/showthread.php?559349-Can-t-log-in-with-Linux-at-the-moment-anybody-else

### CODE REVIEW

**Comment by fuzzybair** [comment]
I am not user how to contact Lynx3d directly so I am posting here. Is pylotro still being maintained? it seems to me that there has been no activity to pylotro (not that it has needed much) or any other project for a year. I understand people get busy would you be willing to accept more contributors to help? or link to a fork from someone else if you do not intend to continue support?

**Comment by fuzzybair** [comment]
has anyone tested with DDO do the changes effect it at all. if so does it still work?

**Comment by nwestfal** [comment]
I have not tested with DDO since I don't play it.  Feel free to test it out!

I made a slight error in the description I think.  The XML changes are most
relevant to launcher.config rather than WorldQueue.config.

**Comment by nwestfal** [comment]
Closing and will re-submit since update 15.1 introduced more changes.

**Pull request closed without merging**
